-- A per-account token, so we can tell WHICH workspace published a delegation.
--
-- ⚠ 0041 MADE THE ZONE EXCLUSIVE BUT COULD NOT MAKE IT CORRECT, and the gap was
-- the records themselves. Every delegating customer is told to publish the same
-- two nameservers — `ns1.i10.tech` and `ns2.i10.tech` — so nothing in what
-- reaches DNS identifies the account it came from. The claim therefore fell to
-- arrival order, which is not evidence of anything:
--
--   1. a stranger adds `pslhq.app`, picks delegation, publishes nothing;
--   2. the real owner adds `pslhq.app` and publishes the NS records;
--   3. the owner's delegation resolves to the STRANGER'S zone, carrying the
--      stranger's DKIM selector, and SES verifies the stranger.
--
-- The owner did everything right and handed over their domain by doing it.
--
-- ⚠ AND THE PROOF CANNOT LIVE UNDER THE DELEGATED NAMES. `mail.<domain>`,
-- `_domainkey.<domain>` and `_dmarc.<domain>` are served by US the moment the
-- delegation exists, so a token placed in any of them is a token we wrote
-- ourselves. It proves the zone answers, which was never in doubt. The
-- challenge has to sit in a name the CUSTOMER'S nameservers answer —
-- `_i10-challenge.<domain>` — which is why it is one label to the side of
-- everything else we ask for.
--
-- ⚠ GENERATED BY THE DATABASE, NOT THE APPLICATION, so a row cannot exist
-- without one. `gen_random_uuid()` is volatile, so ADD COLUMN evaluates it per
-- row and every existing domain is backfilled with its own value rather than
-- all of them sharing one — which would make the token worthless for exactly
-- the domains that already exist.
ALTER TABLE "core"."domains"
  ADD COLUMN "delegation_token" text NOT NULL
  DEFAULT replace(gen_random_uuid()::text, '-', '');
--> statement-breakpoint

-- ⚠ THE CLAIM MOVES FROM `create` TO `verify`, so a claim taken before this
-- migration was taken on arrival order and stands on nothing. Releasing them
-- costs the holders one press of Verify — they re-prove and take it back — and
-- leaving them would grandfather in exactly the squat this closes.
--
-- ⚠ THE ZONES IN `pdns` ARE LEFT ALONE ON PURPOSE. Dropping them would stop a
-- legitimate customer's mail resolving for as long as it takes them to notice;
-- an unclaimed zone answers with records nobody can send with until somebody
-- proves the name, and `verify` overwrites it wholesale at that point.
DELETE FROM "core"."delegations";
