apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: i10-redis
  namespace: i10-prod
spec:
  project: i10
  source:
    repoURL: git@github.com:i10-tech/i10.git
    targetRevision: main
    path: infra/k8s/i10/redis
  destination:
    server: https://kubernetes.default.svc
    namespace: i10-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
