import { generateKeyPairSync, randomBytes } from "node:crypto"

/**
 * DKIM keys, generated by us.
 *
 * ⚠ BYODKIM, NOT EASY DKIM, AND IT IS NOT A PREFERENCE — IT IS THE ONLY OPTION
 * THAT LETS US CHOOSE THE ROUTE. With Easy DKIM, Amazon generates the keypair
 * and holds the private half, so only Amazon can sign for the domain. The
 * moment a message is meant to leave through our own MTA instead, there is no
 * key to sign it with, and the customer would have to publish a second set of
 * records to switch. Owning the key is what makes "we decide, per message,
 * whether this goes via SES or direct" possible at all.
 *
 * `core.domains` has said so since it was written: selector and public key are
 * columns, and the private key is explicitly not one.
 *
 * ⚠ 2048-BIT RSA. SES accepts 1024 or 2048; 1024 has been considered weak for
 * DKIM for years and some receivers now discount it. The cost is a public key
 * too long for a single 255-character DNS string, which is why the record value
 * below is emitted as quoted chunks — every DNS provider joins them back.
 */

export interface DkimKeypair {
  /** The DNS label the key is published under. `<selector>._domainkey.<domain>`. */
  selector: string
  /** base64 SPKI DER. Goes in the TXT record, and is not secret. */
  publicKey: string
  /**
   * base64 PKCS#8 DER — what SES's `DomainSigningPrivateKey` wants.
   *
   * ⚠ THE ONLY SECRET IN THIS FEATURE. Anyone holding it can sign mail as the
   * customer's domain, so it is sealed before it goes anywhere near a row and
   * never returned by the API.
   */
  privateKey: string
}

/**
 * ⚠ THE SELECTOR IS RANDOM, NOT `i10` OR THE DATE. A fixed selector means one
 * name per domain, so rotating a key is a destructive edit of a live record
 * with a propagation window in which nothing verifies. A random one lets the
 * next key be published alongside the old one and cut over when it resolves.
 */
export const generateSelector = (): string => `i10${randomBytes(6).toString("hex")}`

export function generateDkimKeypair(): DkimKeypair {
  const { publicKey, privateKey } = generateKeyPairSync("rsa", {
    modulusLength: 2048,
    publicKeyEncoding: { type: "spki", format: "der" },
    privateKeyEncoding: { type: "pkcs8", format: "der" },
  })

  return {
    selector: generateSelector(),
    publicKey: publicKey.toString("base64"),
    privateKey: privateKey.toString("base64"),
  }
}

/**
 * The TXT value for `<selector>._domainkey.<domain>`.
 *
 * ⚠ SPLIT INTO QUOTED 255-CHARACTER CHUNKS, BECAUSE A 2048-BIT KEY DOES NOT FIT
 * IN ONE. A DNS character-string caps at 255 bytes; a TXT record may hold
 * several and resolvers concatenate them with no separator. Emitting one long
 * unquoted string is the single most common way a DKIM record is published
 * broken — some providers split it for you, some truncate it, and the failure
 * is a signature that never verifies with no error anywhere.
 */
export function dkimRecordValue(publicKey: string): string {
  const record = `v=DKIM1; k=rsa; p=${publicKey}`
  if (record.length <= 255) return record

  const chunks = record.match(/.{1,255}/g) ?? [record]
  return chunks.map((chunk) => `"${chunk}"`).join(" ")
}
